version: "3.8"

services:
  mysql:
    container_name: mysql-finance
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: finance
    ports:
      - "3307:3306"
    volumes:
      - mysql_finance:/var/lib/mysql
    networks:
      - api

  app:
    container_name: api-finance
    image: matheusabd/finance-api
    ports:
      - "8080:8080"
    networks:
      - api
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/finance?createDatabaseIfNotExist=true
    depends_on:
      - mysql
      
volumes:
  mysql_finance:

networks:
  api:
   